apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sudoku-solver
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sudoku-solver
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sudoku-solver
spec:
  selector:
    matchLabels:
      app: sudoku-solver
  replicas: 1
  template:
    metadata:
      labels:
        app: sudoku-solver
    spec:
      containers:
      - name: sudoku-solver
        image: captaincontainer/sudoku-solver:latest
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: sudoku-solver
spec:
  selector:
    app: sudoku-solver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  loadBalancerIP: $LB_IP
  type: LoadBalancer
